framework:
    cache:
        prefix_seed: '%env(APP_ENV)%:exrate'
        app: cache.adapter.redis
        system: cache.adapter.apcu
        default_redis_provider: '%env(REDIS_URL)%'
        default_pdo_provider: '%env(resolve:DATABASE_URL)%'
        # Namespaced pools use the above "app" backend by default
        pools:
            tags_cache:
                adapter: cache.adapter.redis
                default_lifetime: 86400
                tags: apcu_cache
            apcu_cache:
                adapter: cache.adapter.apcu
            fast_cache:
                adapters:
                    - cache.adapter.apcu
                    - cache.adapter.redis
                default_lifetime: 86400
            first_cache:
                adapter: app.cache.default
                default_lifetime: 0
                provider: '%env(REDIS_URL)%/1'
            second_cache:
                adapter: app.cache.default
                default_lifetime: 0
                provider: '%env(REDIS_URL)%/2'
            third_cache:
                adapter: app.cache.default
                default_lifetime: 0
                provider: '%env(REDIS_URL)%/3'
            fourth_cache:
                adapter: app.cache.default
                default_lifetime: 0
                provider: '%env(REDIS_URL)%/4'
            ## Example cache: with namespace (Dont touch)
            #example_cache:
            #    adapter: app.cache.adapter.example_cache
            #    default_lifetime: 3600
            #    provider: '%env(REDIS_URL)%/4'
