framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true
    http_client:
        default_options:
            max_redirects: 7
    #session:
    #    handler_id: null
    #    cookie_secure: auto
    #    cookie_samesite: lax
    #    storage_factory_id: session.storage.factory.native


    lock: true
    php_errors:
        log: true
        throw: true
    serializer:
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
