nelmio_api_doc:
    documentation:
        info:
            title: Exchange Rate API
            description: API for fetching exchange rates.
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
