framework:
    rate_limiter:
        provider:
            policy: 'fixed_window'
            limit: 1
            interval: '1 seconds'
            lock_factory: 'lock.factory'
        anonymous_api:
            # use 'sliding_window' if you prefer that policy
            policy: 'fixed_window'
            limit: 100
            interval: '10 minutes'
        authenticated_api:
            policy: 'token_bucket'
            limit: 1000
            rate: { interval: '10 minutes', amount: 500 }
        api_rate:
            policy: 'fixed_window'
            limit: 10
            interval: '60 seconds'
        api_timeseries:
            policy: 'fixed_window'
            limit: 20
            interval: '120 seconds'
